### ISSUE TITLE
ECS Services and deploy Docker instances

### ISSUE THREAD

**Issue by pentateu** [arminc/terraform-ecs#15]
I believe you will cover this in your "Micro services example" issue, but I'll ask here anyway.

I don't see in the instance you deploy where you specify the ECS service and the docker image for it.

**Comment by arminc** [comment]
I am not sure I understand the question but if you are asking how to deploy a Docker container then you can have a look here https://github.com/arminc/terraform-ecs/tree/master/deployment.

In the https://github.com/arminc/terraform-ecs/blob/master/deployment/service-create-nginx.json you can see that the cluster is specified there

**Comment by pentateu** [comment]
got it. Thanks I was missing a few links between the pieces, with your example is clear now.
Thanks

**Comment by arminc** [comment]
I am glad you solved it
