### ISSUE TITLE
Rename resource to http

### ISSUE THREAD

**Issue by 13o6** [arminc/terraform-ecs#20]
https://github.com/arminc/terraform-ecs/blob/fe4bd736568ebe91052bdfe83014e966cb02935f/modules/alb/main.tf#L30

I don't understand why that resource is confusingly called `https`. Please update accordingly.

**Comment by astanciu** [comment]
Any reason this issue is still open? Doesn't #22 close it?

**Comment by arminc** [comment]
You are right @astanciu
